# Generated by Django 5.1.4 on 2025-01-19 11:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='destination',
            new_name='end_point',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='origin',
            new_name='route_name',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='bus_name',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='total_seats',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='address',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='user',
        ),
        migrations.RemoveField(
            model_name='route',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='route',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='route',
            name='price',
        ),
        migrations.RemoveField(
            model_name='route',
            name='travel_date',
        ),
        migrations.AddField(
            model_name='bus',
            name='capacity',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='bus',
            name='type',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Standard', 'Standard'), ('Mini', 'Mini')], default='Standard', max_length=20),
        ),
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='password',
            field=models.CharField(default='1234', max_length=255),
        ),
        migrations.AddField(
            model_name='passenger',
            name='username',
            field=models.CharField(default='username', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='route',
            name='bus_type',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Standard', 'Standard'), ('Mini', 'Mini')], default='Standard', max_length=20),
        ),
        migrations.AddField(
            model_name='route',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='route',
            name='estimated_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='route',
            name='price_tzs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='route',
            name='starting_point',
            field=models.CharField(default='Nugwi', max_length=100),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField(default=django.utils.timezone.now)),
                ('travel_time', models.TimeField(default='00:00:00')),
                ('seat_number', models.PositiveIntegerField(default=1)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.bus')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.passenger')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.route')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('seat_number', models.PositiveIntegerField(default=1)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled')], default='Booked', max_length=20)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.bus')),
            ],
        ),
        migrations.DeleteModel(
            name='BookingTicket',
        ),
    ]
