# Generated by Django 5.1.3 on 2025-01-19 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='booking.route'),
        ),
    ]
