# Generated by Django 5.1.3 on 2025-01-26 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bus_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bus'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.passenger'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.route'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='travel_time',
            field=models.TimeField(),
        ),
    ]
